# ===================================================================
# Tracing Service configuration
# ===================================================================

server:
  port: 9411

zipkin:
  self-tracing:
    enabled: true